### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by renmengwen** [Veryan4/d-rummy#1]
hey Veryan，I cloned your project from GitHub, but there was an error when starting it: 'lit not fonud'. I found that there was no lit-related dependency in pakes.json, so I downloaded it, but when I executed pnpm dev, the error shown in the picture was displayed. Can you help me solve it?
![1724668014881](https://github.com/user-attachments/assets/976468fc-0019-430d-8786-a7262d6449a0)

**Comment by Veryan4** [comment]
I’ll look at this tomorrow morning. In the meantime try running ‘npm i’ before running ‘npm dev’ to make sure all of the dependencies of the project are installed

**Comment by Veryan4** [comment]
Hi @renmengwen, I tried a couple of different ways and installing the node dependencies via `npm i` before running the project with `npm run dev` seems to do the trick. If it's still not working for you please let me know which OS you're running and what the version is. Please also provide your version of node and npm. Thanks.

**Comment by Veryan4** [comment]
Forgot to update github, but had a back and forth with @renmengwen via email a week ago and it turns out the issue was that the loading of languages had a bug and only accounted for english and french. After updating the lit-spa library with a fix to allow for any unrecognized browser language to be defaulted to english, this was resolved in the commit 6ee0d2 on August 28th 2024
